export const parts = [
    {
        title: "Design Guidelines",
        innerColumns: 4,
        size: 4,
        category: true,
        parts: [
            {
                title: "Design Philosophy",
            },
            {
                title: "Component design",
                parts: ["Componentizing", "Components in Figma", "Auto layout"]
            },
            {
                title: "Naming",
                parts: ["UI elements", "Layers"]
            },
            {
                title: "Cross-panel design",
                parts: ["Guidelines", "Custom vs Native"],
            }
        ]
    },
    {
        title: "Foundation",
        innerColumns: 4,
        size: 4,
        category: true,
        parts: [
            {
                title: "Design tokens",
                parts: ["Tokens types", "Naming convention", "Tokens tooling", "Examples"]
            },
            {
                title: "Color",
                parts: ["Principles", "Palettes", "Contrast", "Meaning", "Swatches", "Accessibility"],
            },
            {
                title: "Typography",
                parts: ["Headings", "Weights / types", "Web fonts", "Baseline grid", "Responsive text"],
            },
            {
                title: "Iconography",
                parts: ["Icons", "Illustration", "Alignment"],
            },
            {
                title: "Motion",
                parts: ["Concept", "Timing", "Types", "Transitions", "Availability"],
            },
            {
                title: "Space",
                parts: ["Units / measurments", "Metrics and keylines", "Structure"],
            },
            "Border radius",
        ],
    },
    {
        title: "UI elements",
        innerColumns: 4,
        size: 4,
        category: true,
        parts: [
            "Paragraph",
            "Lead paragraph",
            "Block quote",
            "Headers (H1 - H6)",
            "Lists",
            "Links",
            "Code",
            "Divider / rule",
            {
                title: "Buttons",
                parts: [
                    "Primary",
                    "Secondary",
                    "Button groups",
                    "Menu buttons",
                    "Split buttons",
                    "FAB (floating action)",
                ],
            },
            {
                title: "Image",
                parts: ["Block", "Full bleed", "Inline with positions", "Circled"],
            },
            {
                title: "Form controls",
                parts: [
                    "Text",
                    "Input",
                    "Text area",
                    "Radio",
                    "Checkbox",
                    "Select",
                    "File upload",
                    "Labels",
                    "Floating labels",
                    "Microcopy",
                    "Required",
                    "Validation",
                ],
            },
        ],
    },
    {
        title: "UI components",
        innerColumns: 4,
        size: 4,
        category: true,
        parts: [
            "Action bar/sheet",
            "Back to top",
            "Badge",
            "Breadcrumbs",
            "Calendar picker",
            "Caption",
            "Cards",
            "Chat (live)",
            "Code block",
            "Comments",
            "Contact us",
            "Cookie notification",
            "Data tables",
            "Dialog",
            "Drawer/accordion",
            "Filters",
            "Footer",
            "Footnotes",
            "Header",
            "Hero billboard",
            "Hero carousel",
            "Legend",
            "Loading / spinner",
            "Local navigation",
            "Maps",
            "Menu",
            {
                title: "Messaging",
                parts: ["Toast", "Block", "Inline error"],
            },
            "Modal",
            "Nav Megamenu",
            "Pagination",
            "Progress bar",
            "Pull quote",
            "Ratings",
            "Reviews",
            "Rich text editor",
            "Search",
            "Sidebar",
            "Site/App navigation",
            "Slider",
            "Social networking",
            "Status (alpha, beta,...)",
            "Switch",
            "Tabs",
            "Tags / chips / pills",
            "Thumbnails / #-ups",
            "Tips / tutorial",
            "Toolbar",
            "Tooltips",
            "Video & media",
        ],
    },
    {
        title: "UI patterns",
        size: 2,
        innerColumns: 2,
        category: true,
        parts: [
            "Authentication",
            "Chatbots",
            "Create account",
            "Database connection",
            "Exporting",
            "Form structure",
            "Generating keys",
            "Importing",
            "Launch",
            "Lists",
            "Navigation",
            "Onboarding",
            "Permissions",
            "Purchase/checkout",
            "Removing",
            "Settings",
            "Site / app structure",
            "Swipe to refresh",
        ],
    },
    {
        title: "View templates",
        category: true,
        innerColumns: 2,
        size: 2,
        parts: [
            "Home",
            "Category",
            "Product",
            "Dashboard",
            "Article",
            "Search results",
            "Contact us",
            "Getting started",
            "Discussion",
            "Gallery",
        ],
    },
    {
        title: "Layout system",
        size: 2,
        category: true,
        parts: [
            "Grids for sites",
            "Grids for apps",
            "Paneling/transitions",
            "Responsive/breakpoints",
            "Screen sizes",
        ],
    },
    {
        title: "Editorial",
        category: true,
        parts: [
            "Voice & tone",
            "Writing for the web",
            "Word list",
            "Capitalization",
            "Punctuation",
        ],
    },
    {
        title: "Branding",
        category: true,
        parts: ["Identity", "Logo(s)", "Tagline(s)", "Partnerships", "Themes"],
    },
    {
        title: "Research & users",
        category: true,
        parts: [
            "User needs",
            "Personas",
            "Research techniques",
            "Surveys",
            "A/B, multivar. testing",
        ],
    },
    {
        title: "Practices",
        category: true,
        parts: [
            "Accessibility",
            "Prototyping",
            "Performance",
            "Reviews",
            "Design thinking",
        ],
    },
    {
        title: "Coding standards",
        category: true,
        parts: [
            "Style",
            "Browsers & devices",
            "Environments",
            "Prog. enhancement",
            "Version control",
        ],
    },
    {
        title: "Downloads",
        category: true,
        parts: ["Templates (PSD,...)", "Swatch palettes", "Fonts", "Icons", "Code"],
    },
    {
        title: "Getting involved",
        category: true,
        parts: [
            "Request New Parts",
            "Give Feedback",
            "Request Audit",
            "Present at a Share",
            "Contribute",
        ],
    },
    {
        title: "About the system",
        category: true,
        parts: [
            "Home page",
            "Principles / pillars",
            "Getting started",
            "FAQ",
            "Changelog",
        ],
    },
    {
        title: "About the team",
        category: true,
        parts: ["People in the team", "Holiday schedule", "Design System Café", "Partners", "Join us"],
    },
    {
        title: "Utilities",
        category: true,
        parts: ["Packages", "Licenses", "Mixins", "Helpers", "Customize"],
    },
];

export const getInputName = (str1, str2) => {
    return [str1, "_", str2].map((str) => str.replace(/\s/g, "-")).join("");
};