name: deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            
      - name: Install dependencies
        run: yarn install
        
      - name: Build
        run: yarn build
        
      - name: Export static files for main site
        run: yarn export
        
      - name: Export hands-on workshop files
        run: yarn export:hands-on-workshop
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          folder: ./out
          branch: gh-pages
          clean: true
          clean-exclude: .nojekyll
       
       
      - name: Archive hands-on-workshop export as artifact
        uses: actions/upload-artifact@v2
        with:
          name: hands-on-workshop
          path: |
            hands-on-workshop/
            
  deploy-workshop:
    runs-on: ubuntu-18.04
    needs: deploy
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact of hands-on-workshop export
        uses: actions/download-artifact@v2
        with:
          name: hands-on-workshop
          path: hands-on-workshop/
        
      - run: ls
          
      - name: Deploy hands-on-workshop.goright.io
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          folder: hands-on-workshop/
          repository-name: goright-io/hands-on-workshop.goright.io
          token: ${{ secrets.GH_PAT }}
          branch: gh-pages
          clean: true
          clean-exclude: .nojekyll
            
      